version: '3.8'

services:
  agent-kit:
    build: 
      context: ..       
      dockerfile: Dockerfile
    container_name: agent-kit
    environment:
      - RPC_URL=${RPC_URL}
    ports:
      - "8080:8080"
      - "9090:9090"
    networks:
      - agent-net


networks:
  agent-net:
    driver: bridge